f

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,7 +1,17 @@
 version: 2.1
 
+orbs:
+  slack: circleci/slack@4.9.3
+
+
 commands:
-  install_awscli:
+   notify_on_failure:
+      steps:
+        - slack/notify:
+            event: fail
+            channel: cicd-pipeline
+            template: basic_fail_1
+   install_awscli:
       description: Install AWS CLI v2
       steps:
       - run:
@@ -10,21 +20,20 @@ commands:
             curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
             unzip awscliv2.zip
             sudo ./aws/install
-
-  install_ansible:
+   install_ansible:
       description: Install Ansible 
       steps:
-      - run:
+       - run:
           name: Install Ansible 
           command: |
             sudo apt update
             sudo apt install software-properties-common -y
             sudo add-apt-repository --yes --update ppa:ansible/ansible
             sudo apt install ansible -y
-  install_nodejs:
+   install_nodejs:
       description: Install Node.js 13
       steps:
-      - run:
+       - run:
           name: Install Node.js 13
           command: |
             sudo apt update -y && curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
@@ -32,12 +41,14 @@ commands:
             
             sudo npm install --global n
             sudo n 13.8.0 
-  destroy-environment:
+
+   destroy-environment:
       description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
       parameters:
         Workflow_ID:
           type: string 
           default: "${CIRCLE_WORKFLOW_ID:0:7}"   
+      
       steps:
         - run:
             name: Destroy environments
@@ -46,8 +57,8 @@ commands:
               aws cloudformation delete-stack --stack-name udapeople-backend-<< parameters.Workflow_ID >>
               aws s3 rm s3://udapeople-<<parameters.Workflow_ID>> --recursive
               aws cloudformation delete-stack --stack-name udapeople-frontend-<< parameters.Workflow_ID >>
-            
-  revert-migrations:
+
+   revert-migrations:
       description: Revert the last migration if successfully run in the current workflow.
       parameters:
         Workflow_ID:
@@ -65,201 +76,180 @@ commands:
               npm install
               npm run migration:revert
             fi
+            
 jobs:
   build-frontend:
     docker:
-      - image: circleci/node:13.8.0
+      - image: cimg/node:13.8.0
     steps:
       - checkout
       - restore_cache:
-          keys: [frontend-build]
+          keys: [frontend-deps]
       - run:
           name: Build front-end
           command: |
-            # Your code here
             cd frontend
             npm install
-            npm run build
+            npm build
       - save_cache:
           paths: [frontend/node_modules]
-          key: frontend-build
+          key: frontend-deps
+      - notify_on_failure
 
   build-backend:
     docker:
-      - image: circleci/node:13.8.0
+      - image: cimg/node:13.8.0
     steps:
       - checkout
       - restore_cache:
-          keys: [backend-build]
+          keys: [backend-deps]
       - run:
           name: Back-end build
           command: |
-             # Your code here
              cd backend
              npm install
              npm run build
       - save_cache:
           paths: [backend/node_modules]
-          key: backend-build
+          key: backend-deps
+      - notify_on_failure
 
   test-frontend:
     docker:
-      - image: circleci/node:13.8.0
+      - image: cimg/node:13.8.0
     steps:
       - checkout
       - restore_cache:
-          keys: [frontend-test]
+          keys: [frontend-deps]
       - run:
-          name: test front-end
+          name: Front-end Unit Test
           command: |
-            # Your code here
-            cd frontend
-            npm install
-            npm run test
-      - save_cache:
-          paths: [frontend/node_modules]
-          key: frontend-test
-        
+             cd frontend
+             npm install
+             npm test
+      - notify_on_failure               
   test-backend:
     docker:
-      - image: circleci/node:13.8.0
+      - image: cimg/node:13.8.0
     steps:
       - checkout
       - restore_cache:
-          keys: [backend-test]
+          keys: [backend-deps]
       - run:
-          name: test back-end
+          name: Back-end Unit Test
           command: |
-            # Your code here
-            cd backend
-            npm install
-            npm run test
+             cd backend
+             npm install
+             npm test
+      - notify_on_failure
       - save_cache:
           paths: [backend/node_modules]
-          key: backend-test
+          key: backend-deps
             
   scan-frontend:
     docker:
-      - image: circleci/node:13.8.0
+      - image: cimg/node:13.8.0
     steps:
       - checkout
       - restore_cache:
-          keys: [scan-frontend]
+          keys: [frontend-deps]
       - run:
-          name: scan-front-end
+          name: Front-end Unit Scan
           command: |
-            cd frontend
-            npm install
-            # npm install oauth-sign@^0.9.0
-            npm audit fix --audit-level=critical --force
-            npm audit --audit-level=critical
-      - save_cache:
-          paths: [frontend/node_modules]
-          key: scan-frontend
-
+             cd frontend
+             npm install
+             npm audit fix --force --audit-level=critical
+             npm audit --audit-level=critical
+      - notify_on_failure
   scan-backend:
     docker:
-      - image: circleci/node:13.8.0
+      - image: cimg/node:13.8.0
     steps:
       - checkout
       - restore_cache:
-          keys: [scan-backend]
+          keys: [backend-deps]
       - run:
-          name: scan-back-end
+          name: Back-end Unit Scan
           command: |
-            cd backend
-            npm install
-            # npm install oauth-sign@^0.9.0
-            npm audit fix --audit-level=critical --force
-            npm audit fix --audit-level=critical --force
-            npm audit fix --force
-            npm audit --audit-level=critical
-      - save_cache:
-          paths: [backend/node_modules]
-          key: scan-backend
-
+             cd backend
+             npm install
+             npm audit fix --force --audit-level=critical
+             npm audit fix --force --audit-level=critical
+             npm audit --audit-level=critical
+      - notify_on_failure
   deploy-infrastructure:
     docker:
-      - image: amazon/aws-cli
+    - image: cimg/base:stable
     steps:
       - checkout
-      - run:
-          name: Install dependencies
-          command: |
-            yum install -y tar gzip
+      - install_awscli
       - run:
           name: Ensure back-end infrastructure exists
           command: |
             aws cloudformation deploy \
-            --template-file .circleci/files/backend.yml \
-            --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-            --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
-            --tags project=udapeople
-      
+              --template-file .circleci/files/backend.yml \
+              --tags project=udapeople \
+              --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  
+              
       - run:
           name: Ensure front-end infrastructure exist
           command: |
             aws cloudformation deploy \
-            --template-file .circleci/files/frontend.yml \
-            --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
-            --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
-            --tags project=udapeople\
-
+              --template-file .circleci/files/frontend.yml \
+              --tags project=udapeople \
+              --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}" \
+      
       - run:
           name: Add back-end ip to ansible inventory
           command: |
-            cd .circleci/ansible
-            cat inventory.txt
-            aws ec2 describe-instances \
-              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --query 'Reservations[*].Instances[*].PublicIpAddress' \
-              --output text >> inventory.txt
-            cat inventory.txt
-            # export BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
-            #   --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-            #   --query 'Reservations[*].Instances[*].PublicIpAddress' \
-            #   --output text)
-            # echo "export BACKEND_PUBLIC_IP=${BACKEND_PUBLIC_IP}" >> $BASH_ENV
-
+            BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+               --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+               --query 'Reservations[*].Instances[*].PublicIpAddress' \
+               --output text)
+            echo $BACKEND_PUBLIC_IP >> .circleci/ansible/inventory.txt
+            cat .circleci/ansible/inventory.txt
       - persist_to_workspace:
           root: ~/
           paths:
             - project/.circleci/ansible/inventory.txt
+      - notify_on_failure
+      - destroy-environment
       # Here's where you will add some code to rollback on failure      
 
   configure-infrastructure:
-      docker:
-        - image: cimg/base:stable
-          # environment:
-          #   NODE_ENV: "production"
-          #   VERSION: "1"
-          #   ENVIRONMENT: "production"
-          #   TYPEORM_CONNECTION: $TYPEORM_CONNECTION
-          #   TYPEORM_HOST: $TYPEORM_HOST
-          #   TYPEORM_USERNAME: $TYPEORM_USERNAME
-          #   TYPEORM_PASSWORD: $TYPEORM_PASSWORD
-          #   TYPEORM_DATABASE: $TYPEORM_DATABASE
-          #   TYPEORM_PORT: $TYPEORM_PORT
-          #   TYPEORM_MIGRATIONS_DIR: "./migrations"
-          #   TYPEORM_ENTITIES: "./modules/domain/**/*.entity{.ts,.js}"
-          #   TYPEORM_MIGRATIONS: "./migrations/*.ts"
-      steps:
-        - checkout
-        - install_ansible
-        - add_ssh_keys:
-            # fingerprints: ["3d:b0:37:65:e9:fb:00:bb:1d:ae:8a:97:0c:22:e3:5a"]
-            fingerprints: ["a4:20:8b:d6:26:fd:8d:bb:34:26:60:20:e0:68:51:3d"]
-        - attach_workspace:
-            at: ~/
-
-        - run:
-            name: Configure server
-            command: |
-              cd .circleci/ansible
-              cat inventory.txt 
-              ansible-playbook -i inventory.txt configure-server.yml
-        - destroy-environment
-  #       # Here's where you will add some code to rollback on failure 
+    docker:
+      - image: cimg/base:stable
+        # environment:
+        #   NODE_ENV: "production"
+        #   VERSION: "1"
+        #   ENVIRONMENT: "production"
+        #   TYPEORM_CONNECTION: $TYPEORM_CONNECTION
+        #   TYPEORM_HOST: $TYPEORM_HOST
+        #   TYPEORM_USERNAME: $TYPEORM_USERNAME
+        #   TYPEORM_PASSWORD: $TYPEORM_PASSWORD
+        #   TYPEORM_DATABASE: $TYPEORM_DATABASE
+        #   TYPEORM_PORT: $TYPEORM_PORT
+        #   TYPEORM_MIGRATIONS_DIR: "./migrations"
+        #   TYPEORM_ENTITIES: "./modules/domain/**/*.entity{.ts,.js}"
+        #   TYPEORM_MIGRATIONS: "./migrations/*.ts"
+    steps:
+      - checkout
+      - install_ansible
+      - add_ssh_keys:
+          # fingerprints: ["3d:b0:37:65:e9:fb:00:bb:1d:ae:8a:97:0c:22:e3:5a"]
+          fingerprints: ["a4:20:8b:d6:26:fd:8d:bb:34:26:60:20:e0:68:51:3d"]
+      - attach_workspace:
+          at: ~/
+      - run:
+          name: Configure server
+          command: |
+            cd .circleci/ansible
+            cat inventory.txt 
+            ansible-playbook -i inventory.txt configure-server.yml
+      - destroy-environment
+#       # Here's where you will add some code to rollback on failure      
 
   run-migrations:
     docker:
@@ -320,22 +310,35 @@ jobs:
             npm run build
             aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
             
-      # - notify_on_failure
+      - notify_on_failure
       - destroy-environment
       - revert-migrations 
-
-  #       # Here's where you will add some code to rollback on failure      
-                  
+ 
+#       # Here's where you will add some code to rollback on failure      
+                    
   deploy-backend:
     docker:
       - image: cimg/base:stable
+        environment:
+         NODE_ENV: "production"
+         VERSION: "1"
+         ENVIRONMENT: "production"
+         TYPEORM_CONNECTION: $TYPEORM_CONNECTION
+         TYPEORM_HOST: $TYPEORM_HOST
+         TYPEORM_USERNAME: $TYPEORM_USERNAME
+         TYPEORM_PASSWORD: $TYPEORM_PASSWORD
+         TYPEORM_DATABASE: $TYPEORM_DATABASE
+         TYPEORM_PORT: $TYPEORM_PORT
+         TYPEORM_MIGRATIONS_DIR: "./migrations"
+         TYPEORM_ENTITIES: "./modules/domain/**/*.entity{.ts,.js}"
+         TYPEORM_MIGRATIONS: "./migrations/*.ts"
     steps:
       - checkout
       - install_awscli
       - install_ansible
       - install_nodejs
       - add_ssh_keys:
-          fingerprints: ["77:09:6b:cd:5a:99:14:f0:e2:c5:01:01:79:73:6b:1c"]
+          fingerprints: ["3d:b0:37:65:e9:fb:00:bb:1d:ae:8a:97:0c:22:e3:5a"]
       - attach_workspace:
           at: ~/
       - restore_cache:
@@ -356,6 +359,7 @@ jobs:
       - run:
           name: Deploy backend
           command: |
+
             export TYPEORM_MIGRATIONS_DIR=./migrations
             export TYPEORM_ENTITIES=./modules/domain/**/*.entity{.ts,.js}
             export TYPEORM_MIGRATIONS=./migrations/*.ts
@@ -363,39 +367,45 @@ jobs:
             cd .circleci/ansible
             cat inventory.txt
             ansible-playbook -i inventory.txt deploy-backend.yml
+
+      - notify_on_failure
+      - destroy-environment
+      - revert-migrations  
+#       # Here's where you will add some code to rollback on failure  
+
   smoke-test:
-      docker:
-        - image: cimg/base:stable
-      steps:
-        - checkout
-        - install_awscli
-        - install_nodejs
-        - run:
-            name: Backend smoke test.
-            command: |
-              export BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
-                --filters "Name=tag:Name, Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-                --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
-              export API_URL="http://${BACKEND_PUBLIC_IP}:3030"
-              echo "${API_URL}"
-              if curl "${API_URL}/api/status" | grep "ok"
-              then
-                exit 0
-              else
-                exit 0
-              fi
-        - run:
-            name: Frontend smoke test.
-            command: |
-              FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com         
-              if curl -s ${FRONTEND_WEBSITE} | grep "Welcome"
-              then  
-                exit 0
-              else
-                exit 1
-              fi
-        - destroy-environment
-        - revert-migrations
+    docker:
+      - image: cimg/base:stable
+    steps:
+      - checkout
+      - install_awscli
+      - install_nodejs
+      - run:
+          name: Backend smoke test.
+          command: |
+            export BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+              --filters "Name=tag:Name, Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
+            export API_URL="http://${BACKEND_PUBLIC_IP}:3030"
+            echo "${API_URL}"
+            if curl "${API_URL}/api/status" | grep "ok"
+            then
+              exit 0
+            else
+              exit 1
+            fi
+      - run:
+          name: Frontend smoke test.
+          command: |
+            FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com         
+            if curl -s ${FRONTEND_WEBSITE} | grep "Welcome"
+            then  
+              exit 0
+            else
+              exit 1
+            fi
+      - destroy-environment
+      - revert-migrations 
 
   cloudfront-update:
     docker:
@@ -412,6 +422,7 @@ jobs:
               --no-paginate --output text)
             echo "Old Workflow ID: ${OLD_WORKFLOW_ID}"
             curl https://kvdb.io/${KVDB_BUCKET}/old_workflow_id -d "${OLD_WORKFLOW_ID}"
+      
       - run:
           name: Update cloudfront distribution
           command: |
@@ -419,9 +430,9 @@ jobs:
             --template-file .circleci/files/cloudfront.yml \
             --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
             --stack-name InitialStack
+
       - destroy-environment
       - revert-migrations
-  
   
   cleanup:
     docker:
@@ -446,7 +457,15 @@ jobs:
             else
               echo "-------------Nothing to Cleanup-------------"
             fi
-            
+
+  notify_on_success:        
+    docker:
+      - image: cimg/base:stable
+    steps:
+      - slack/notify:
+          event: pass
+          channel: cicd-pipeline
+          template: success_tagged_deployment_1
 
 workflows:
   default:
@@ -461,6 +480,13 @@ workflows:
           requires: [build-backend]
       - scan-frontend:
           requires: [build-frontend]
+      - notify_on_success:
+          requires:
+            - test-frontend
+            - test-backend
+            - scan-frontend
+            - scan-backend
+            
       - deploy-infrastructure:
           requires: [test-frontend, test-backend, scan-frontend, scan-backend]
           filters:
@@ -480,3 +506,8 @@ workflows:
           requires: [smoke-test]
       - cleanup:
           requires: [cloudfront-update]
+
+    # sudo apt-get update -y && curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash -
+            # sudo apt-get install -y nodejs 
+            # sudo npm install --global n
+            # sudo n 13.8.0 
